name: PowerDNS External
description: |
  Rancher External DNS service for PowerDNS
version: v0.5.0-rancher1
category: External DNS
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
