version: '2'
services:
  bamboo-server-lb:
    image: rancher/load-balancer-service
    links:
      - bamboo-server
    ports:
      - ${lb_http_port}:8085

  bamboo-data:
    net: none
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - /home/bamboo

  bamboo-server:
    image: matisq/bamboo-server:5.15.3
    hostname: bamboo-server
    extra_hosts:
      - "bamboo-server:127.0.0.1"
    links:
      - postgres
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      BAMBOO_VERSION: ${bamboo_version}
      BAMBOO_BAMBOO_SERVER_ID: bamboo-server
    labels:
      io.rancher.sidekicks: bamboo-data
    volumes_from:
      - bamboo-data

  postgres-data:
    net: none
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - /var/lib/postgresql/data/pgdata

  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    tty: true
    stdin_open: true
    labels:
      io.rancher.sidekicks: postgres-data
    volumes_from:
      - postgres-data

  bamboo-agent:
    image: matisq/bamboo-agent:5.15.3
    links:
      - bamboo-server
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      AGENT_VERSION: ${bamboo_version}
      BAMBOO_SERVER: bamboo-server
      BAMBOO_SERVER_PORT: 8085
      PACKAGES: ${packages}
      no_proxy: bamboo-server
